name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: "Tests"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - run: pnpm build
      - name: Lint
        run: pnpm lint
      - name: Run Tests
        run: pnpm test

  floating:
    name: "Floating Dependencies"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install --no-lockfile
      - run: pnpm build
      - name: Run Tests
        run: pnpm test

  types-scenarios:
    name: "Types: ${{ matrix.tsVersion }}"
    runs-on: ubuntu-latest
    needs: test

    strategy:
      matrix:
        tsVersion:
          - '~5.0'
          - '~5.1'
          - '~5.2'
          - '~5.3'
          - '~5.4'
          - '~5.5'
          - 'beta'
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - run: pnpm build
      - name: Swap TS Version
        run: pnpm add --save-dev typescript@${{ matrix.tsVersion }} --workspace-root
      - name: Check Types
        run: |
          pnpm tsc -v
          pnpm test:types
